# @package _global_
defaults:
  - /config
  - _self_
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    # Multi-objective optimization
    direction:
      - minimize # for train_loss
      - maximize # for coverage

    n_trials: 200
    n_jobs: 1 # Set to -1 for parallel trials

    # Optuna sampler
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 10
      n_startup_trials: 30

    # Optuna study configuration
    study_name: diffusion_flow_study
    storage: null

    # Parameter search space
    params:
      model.lr: interval(1e-5, 1e-2)
      model.weight_decay: interval(1e-4, 1e-2)
      main.batch_size: choice(128, 256, 512)
      model.hidden_dim: choice(128, 256, 512, 1024)
      model.num_layers: choice(2, 5, 10, 15, 20)
      model.time_embed_dim: choice(64, 128, 256, 512)
