# @package _global_
defaults:
  - /config
  - _self_
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    # Multi-objective optimization
    direction:
      - minimize # for train_loss
      - minimize # for fid

    n_trials: 100
    n_jobs: 1 # Set to -1 for parallel trials

    # Optuna sampler
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 10
      n_startup_trials: 15

    # Optuna study configuration
    study_name: diffusion_flow_study_images
    storage: null

    # Parameter search space
    params:
      model.lr: interval(1e-5, 1e-2)
      model.weight_decay: interval(1e-4, 1e-2)
      main.batch_size: choice(128, 256, 512)
      model.hidden_dim: choice(64, 128, 256, 512)
      model.num_layers: choice(2, 4, 6, 8, 10, 12, 15)
